### ISSUE TITLE
Conflicting resources in Istio on application of one ksvc

### ISSUE THREAD

**Issue by treyhyde** [knative-sandbox/net-istio#367]
As per https://groups.google.com/g/knative-users/c/sLsDz2ySCPk/m/6n5PJySQAwAJ

In test envs, ksvcs seems like they are doing what I ask of them,   One major drawback is that it triggers an invalid config for all other unrelated istio proxies and their sync status (istioctl proxy-status) goes “stale.”  Remove the ksvc and the istio proxies can sync again.    istiod complains about 

> ADS:RDS: ACK ERROR sidecar~10.151.148.179~someother-non-knative-service-5fc794b8-rv5x7.devs~devs.svc.cluster.local-179 Internal:Only unique values for domains are permitted. Duplicate entry of domain event-display.devs.svc   

  event-display in this case would be the vanilla event-display out of so many knative examples as defined here:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  labels:
    contrib.eventing.knative.dev/release: "v0.18.1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scaleDownDelay: "10m"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:30d619edd86988a9cd7c0169721c7cd3dba155d58c4eb09c024cf1d1593d4e38
```

So, I'm trying to figure out why istio thinks this ksvc generates duplicate entries?  Any pointers?   Any ksvc I add has this effect.  As long as I have 0 ksvcs, istio is happy, the second I add one, all sidecar proxies break.

> The output of `kubectl get cm -n knative-serving config-istio`
```
kubectl get cm -n knative-serving config-istio
NAME           DATA   AGE
config-istio   2      21d
```
config-istio has the gateway.knative-serving.knative-ingress-gateway set to our custom ingress gw as applied by the knative operator `KnativeServing` CRD.

> - The output of `kubectl get kingress,virtualservice -n $YOUR_APP_NS -o yaml`
```
kubectl get kingress
NAME                               READY   REASON
event-display   True

```

`kubectl get vs` will get you many vs's that reveal developer names.  There are no vs's associated with knative ATM.  We have heavy use of delegate `VirtualService`s 

> Q. A simple helloworld ksvc app without eventing can create the issue? Or does it need eventing (event-display)?

YES, I applied the following ksvc and was able to trigger the same issue... but only in the `devs` NS that I have been experimenting with.   This issue is NOT causes in the `default` NS but I have barely anything going on in the `default` NS.  

BOTH namespaces have these annotations.

 ```
istio-injection=enabled
knative-eventing-injection=enabled
```

BTW, the non-event-display `ksvc` is defined as.

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rusty-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containers:
        - image: treyhyde/hello_world:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "250m"
```

> Q. What is the version of Istio, Knative Serving and Eventing?

Istio: 1.6.12
Knative Serving 0.18
Knative Eventing 0.18

Installed via Knative Operator 0.18

> Q. How did you install Istio? (If possible, please share IstioOperator config.)

istio operator with a few redactions.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: xxx-istiocontrolplane
  namespace: istio-system
spec:
  values:
    gateways:
      istio-ingressgateway:
        type: ClusterIP
    global:
      tracer:
        zipkin:
          address: "xxx-jaeger-collector.monitoring:9411"
    pilot:
      env:
        PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE: true
  profile: minimal
  meshConfig:
    accessLogFile: "/dev/stdout"
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
      tracing:
        sampling: 100
    enablePrometheusMerge: true
  components:
    ingressGateways:
      - name: xxx-ingress-gw
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443
          serviceAnnotations: {}
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-ingressgateway
                    - key: istio
                      operator: In
                      values:
                      - ingressgateway
                  topologyKey: failure-domain.beta.kubernetes.io/zone
          resources:
            limits:
              cpu: 2000m
              memory: 1G
            requests:
              cpu: 500m
              memory: 512M
          hpaSpec:
            minReplicas: 1
            maxReplicas: 5
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-ingressgateway
                    - key: istio
                      operator: In
                      values:
                      - ingressgateway
                  topologyKey: failure-domain.beta.kubernetes.io/zone
          hpaSpec:
            minReplicas: 1
            maxReplicas: 5
  addonComponents:
    kiali:
      enabled: true
    prometheus:
      enabled: true
```
