### ISSUE TITLE
Support gRPC web

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#389]
This is originally created in https://github.com/knative/serving/issues/6478 and moves to net-istio.

gRPC web needs to add:
- an EnvoyFilter resource.
- a corsPolicy in the VirtualService.

Especially corsPolicy most probably needs to be added VirtualService created by net-istio. But there are no way to do that. We need to support it.

**Comment by zhaojizhuang** [comment]
I think we should maintain corspolicy‘s annotation in net-istio?  like [ingress-nginx]( https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors)
knative/serving/issues/10040

**Comment by wSedlacek** [comment]
I was able to get this working using this filter.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-grpc-web-filter
  namespace: istio-system
spec:
  priority: 1
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.cors
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_web
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
```
