### ISSUE TITLE
The resource PeerAuthentication is missing the Knative and Network labels

### ISSUE THREAD

**Issue by houshengbo** [knative-sandbox/net-istio#397]
These labels should be added:
```
labels:
  serving.knative.dev/release: "v0.18.0"
  networking.knative.dev/ingress-provider: istio
```

Both of the resources as below, are missing the labels:
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "webhook"
  namespace: "knative-serving"
spec:
  selector:
    matchLabels:
      app: webhook
  mtls:
    mode: PERMISSIVE
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "istio-webhook"
  namespace: "knative-serving"
spec:
  selector:
    matchLabels:
      app: istio-webhook
  mtls:
    mode: PERMISSIVE
```
