### ISSUE TITLE
Optimize number of Envoy routes created for a single KService

### ISSUE THREAD

**Issue by howardjohn** [knative-sandbox/net-istio#630]
When creating a single kservice, we end up with a lot of Envoy routes. For example, on the local gateway:
```
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.172.17.255.155.sslip.io     /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc.cluster.local           /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default.svc                         /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
http.8081     hello.default                             /*                     hello-ingress.default
```

We get 24 routes. This is 4 variants of the domain X override/no override X 3 variants of the domain (excluding the external one).

I have been looking mostly into the internal gateway, but the external one has similar issues, although a few less matches it seems.

I am investigating this more, opening this issue so I can track what I learn

**Comment by howardjohn** [comment]
One major issue is the matches:
```
  - match:
    - authority:
        prefix: hello.default
      gateways:
      - knative-serving/knative-local-gateway
    - authority:
        prefix: hello.default.svc
      gateways:
      - knative-serving/knative-local-gateway
    - authority:
        prefix: hello.default
      gateways:
      - knative-serving/knative-local-gateway
```

This can actually be reduced to
```
  - match:
    - authority:
        prefix: hello.default
      gateways:
      - knative-serving/knative-local-gateway
```

This reduces the route from 24 -> 8. (very quick and dirty) commit: https://github.com/knative-sandbox/net-istio/commit/f74d21b692023a1b8399f1ccd5b698bc0fe9737c
