### ISSUE TITLE
Ingress Gateway Full Reload Causing High CPU Usage When Adding or Removing Activator from the Path

### ISSUE THREAD

**Issue by diarmuidie** [knative-sandbox/net-istio#645]
We have observed that every time the activator is added or removed from the path it causes Istiod to do a full config push to the ingress gateway. This full push is causing lots of churn and a large CPU utilisation on the ingress gateway and Istiod pods, especially in large clusters with lots of Knative apps which are constantly being added and removed from activators.

### Expected

When Knative adds or removes an activator from the path Istiod should do an incremental update of the Ingress Gateway that only includes the changed routes. 

### Actual

Istiod does a full push because the service accounts have changed (https://github.com/istio/istio/blob/a4ef415822d31c0c79fa3a7267a0e83376f1717f/pilot/pkg/xds/eds.go#L166-L170):
```
info	ads	Full push, service accounts changed, test-app-new-00006.headless-customer.svc.cluster.local
```

Turning on debugging in Istiod we can see that the service account is constantly switching between the deployment SA (`customer-workload`) and the Knative controller SA (`controller`).
```
ads	Updating service accounts now, svc test-app-new-00006.customer.svc.cluster.local, before service account map[spiffe://cluster.local/ns/customer/sa/customer-workload:true], after map[spiffe://cluster.local/ns/knative-serving/sa/controller:true]
```

### Steps to reproduce

1. Create a GKE cluster with pod security policy enabled (I'm not 100% sure if this is related but it is how our clusters with this issue are setup).
2. Install the Istio (I have reproduced this on Istio 1.5.6 and 1.9.1) and Knative (reproduced on 0.20.1 and 0.23.0).
3. Reduce the global `target-burst-capacity` in `config-autoscaler` to "1" to make it easier to get the activator to be added and removed from the path.
4. Deploy the following app:
  ```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-app-new
  namespace: customer

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "3"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      serviceAccountName: customer-workload
      containers:
      - image: gcr.io/knative-samples/helloworld-go
  ```
5. Monitor the Istiod pod logs are the app transitions between `serve` and `proxy` mode to see it doing a full reload each time.
