### ISSUE TITLE
`ListProbeTargets()` does not list probe targets accurately

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#719]
Current [`ListProbeTargets()`](https://github.com/knative-sandbox/net-istio/blob/d7625fa51eb7e53757e4af95bc09ac86f07c921a/pkg/reconciler/ingress/lister.go#L61) does:

1. List Istio Gateways specified in config-istio by `qualifiedGatewayNamesFromContext()`
2. List the ingress service by the Gateway selector.
3. Add the schema (`http` or `https`) defined in the Istio Gateway listed by step-1 to the probe targets.

However, when autoTLS is enabled, Istio Gateways are automatically created by net-istio. So the above process (especially the combination of step-1 & step-3) does not work well.

Step-3 should determine the protocol by `ingress.spec.httpoption`, but net-istio supports manual TLS certs [1] and it will not work in that case.

[1] https://knative.dev/docs/serving/using-a-tls-cert/#manually-adding-a-tls-certificate

**Comment by nak3** [comment]
The another failure scenario is discussed in the slack https://knative.slack.com/archives/C0186KU7STW/p1637206270281700?thread_ts=1637171885.256400&cid=C0186KU7STW

If an Istio Gateway (`knative-ingress-gateway`) has `tls.mode` without `MUTUAL` the prober recoginize the target as TLS and it  tries to probe with `https` scheme.
For example, the following gateway fails. 
```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - example.com
    port:
      name: http-app-http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - example.com
    port:
      name: https-app-https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: app-cert
      mode: MUTUAL
  - hosts:
    - example.com
    port:
      name: https-app-https-simple
      number: 443
      protocol: HTTPS
    tls:
      credentialName: app-cert
      mode: SIMPLE
```
