### ISSUE TITLE
Activator request proxying is incompatible with Istio ClusterRbac

### ISSUE THREAD

**Issue by Cynocracy** [knative-sandbox/net-istio#95]
/area networking

While working through
https://cloud.google.com/solutions/authorizing-access-to-cloud-run-on-gke-services-using-istio#deploying_a_sample_service

A few issues came up:

JWT authorization needs to be disabled on some paths for the system to work (controller being able to ping the service, for example).

With the updated policy:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: tutorial
spec:
  origins:
  - jwt:
      issuer: https://accounts.google.com
      audiences:
      - http://example.com
      jwksUri: https://www.googleapis.com/oauth2/v3/certs
      triggerRules:
      - includedPaths:
        - prefix: /
      - excludedPaths:
        - exact: /_internal/knative/activator/probe
        - exact: /healthz
        - exact: /probe
        - exact: /metrics
  principalBinding: USE_ORIGIN
```

Things *mostly* work, with one large gap.

It was discovered that this example only works when the Activator is not proxying requests. This is pretty clearly non-ideal, and appears to be related to an inability of the Activator to query the health of the (Revision pod and/or ClusterIP).

We should determine how to make Istio JWT authz work properly with Activator proxying in order for users to be able to have scale to zero and burst protection at the same time as locking down Service access via JWT.

**Comment by vagababov** [comment]
I guess in `net-istio` it's all networking :D

**Comment by vagababov** [comment]
/cc @mattmoor 
for visibility

**Comment by vagababov** [comment]
It also probably prohibits Autoscaler to scrape the metrics from the pods, limiting all possible scaling decisions.
I think ideally either specific deployments or everything in `knative-serving` should be whitelisted for these specific paths.

**Comment by Cynocracy** [comment]
> I guess in net-istio it's all networking :D

:)

**Comment by Cynocracy** [comment]
> It also probably prohibits Autoscaler to scrape the metrics from the pods, limiting all possible scaling decisions.

I can take a look, but IIRC controller -> pod and autoscaler -> pod traffic seemed alright.

**Comment by vagababov** [comment]
Controller does not talk to pods, though. Only Autoscaler and Activator do.

**Comment by vagababov** [comment]
As we confirmed Autoscaler can't talk either.

**Comment by nak3** [comment]
I have tested @Cynocracy's setting and the issue seemed replicable on my env. 
Then the issue was fixed if I removed the `includedPaths` from the policy.

To be removed:
```
      - includedPaths:
        - prefix: /
```

Actually our CI tests the policy without [`includedPaths`](https://github.com/knative/serving/blob/e14075aa8b4883c2d6d30c74c08e89ed356e9453/test/config/security/policy.yaml#L39-L55).

With said, in my understanding, having `prefix: /` and the empty list should be same meaning. The Istio docs explains it as:

https://archive.istio.io/v1.4/docs/reference/config/security/istio.authentication.v1alpha1/#Jwt-TriggerRule
> List of paths that the request must include. If the list is not empty, the rule is satisfied if request path matches at least one of the path in the list. If the list is empty, the rule is ignored, in other words the rule is always satisfied.

Anyway could you please verify if removing `includedPaths` solve the issue on your env too?

**Comment by ZhiminXiang** [comment]
I tried removing `includePaths`, things works.

Looks like in the Policy yaml in in https://github.com/knative/net-istio/issues/95#issue-615052497, the rule `includedPaths: prefix: /` will still be triggered even for the requests with excluded paths (e.g. `/_internal/knative/activator/probe`).

I guess Istio tries to match `includedPaths` first. If any path matches, the rule will be triggered. If no paths matches, then it checks `excludedPaths`, which could explain why removing `includedPaths` could make things work.

**Comment by Cynocracy** [comment]
Huh, thanks folks! That was a simpler fix than I had imagined.

I'll test out the change and if all's clear I can close this out.

**Comment by Cynocracy** [comment]
Unfortunately I'm not able to confirm :(

I'm setting up a cluster with the Policy

```
  spec:
    origins:
    - jwt:
        audiences:
        - http://example.com
        issuer: https://accounts.google.com
        jwksUri: https://www.googleapis.com/oauth2/v3/certs
        triggerRules:
        - excludedPaths:
          - prefix: /_internal/knative
          - exact: /healthz
          - exact: /probe
          - exact: /metrics
    principalBinding: USE_ORIGIN
```

I'm still only able to hit the Service when the Activator isn't in the request path. In addition, when it's not in the request path, hitting /healthz returns

`RBAC: access denied`

which is different than the error seen when hitting a protected endpoint:

`Origin authentication failed.`

@nak3 @ZhiminXiang any ideas what could be different about our setups? Are there any resources you create other than the Policy/ClusterRbacConfig/ServiceRole/ServiceRoleBinding?

**Comment by Cynocracy** [comment]
Checking @ZhiminXiang 's example (thanks for sharing!) I see a few differences.

Later Knative version is being used
and the 'Invoker' ClusterRbac etc is missing.

I'll try those out and see if I have any luck :) The main issue there is that those are necessary to enforce 
      request.auth.claims[email]:

But if those end up being problematic... I can shift to playing around with the settings there.

**Comment by Cynocracy** [comment]
Yup, I think those are actually the issue.

```

apiVersion: rbac.istio.io/v1alpha1
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: ON_WITH_INCLUSION
  inclusion:
    namespaces:
    - tutorial
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: invoker
  namespace: tutorial
spec:
  rules:
  - services:
    - '*'
    paths:
    - '*'
    methods:
    - '*'
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: invoker-binding
  namespace: tutorial
spec:
  subjects:
  - properties:
      request.auth.claims[email]: cloudrun-gke-invoker-tutorial@jondonovan-knative.iam.gserviceaccount.com
  roleRef:
    kind: ServiceRole
    name: invoker
```

So now to figure out how to enforce these without making activator -> pod traffic unhappy.

**Comment by Cynocracy** [comment]
```
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: invoker-binding
  namespace: tutorial
spec:
  subjects:
  - properties:
      request.auth.claims[email]: cloudrun-gke-invoker-tutorial@jondonovan-knative.iam.gserviceaccount.com
  - properties:
      source.namespace: "knative-serving"
  roleRef:
    kind: ServiceRole
    name: invoker

```

May do the trick, trying it out now :)

**Comment by Cynocracy** [comment]
No luck (so far). Continuing to prototype.

**Comment by tcnghia** [comment]
@Cynocracy our tests also enable sidecar on Activator, so may be that's another thing to try.

**Comment by Cynocracy** [comment]
Interesting, would labeling the namespace do the trick, or would that be overkill?

**Comment by Cynocracy** [comment]
```
{"level":"error","ts":"2020-05-15T19:48:46.398Z","logger":"activator","caller":"net/revision_backends.go:293","msg":"Failed to probe clusterIP 10.0.15.182:80","knative.dev/controller":"activator","knative.dev/pod":"activator-8678df44f9-bz2kj","knative.dev/key":"tutorial/my-service-00001-cix","error":"unexpected body: want \"queue\", got \"RBAC: access denied\"","stacktrace":"gke-internal/knative/cloudrun/vendor/knative.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests\n\tgke-internal/knative/cloudrun/vendor/knative.dev/serving/pkg/activator/net/revision_backends.go:293\ngke-internal/knative/cloudrun/vendor/knative.dev/serving/pkg/activator/net.(*revisionWatcher).run\n\tgke-internal/knative/cloudrun/vendor/knative.dev/serving/pkg/activator/net/revision_backends.go:335"}
```

:( I'm starting to suspect my "allow traffic from namespace X" bit is failing.

**Comment by Cynocracy** [comment]
OK, after much head desking it turns out the trick is to just completely ignore the deprecated ClusterRbacConfig feature and do it entirely using Authn/AuthzPolicies


```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: tutorial
spec:
  origins:
  - jwt:
      issuer: https://accounts.google.com
      audiences:
      - http://example.com
      jwksUri: https://www.googleapis.com/oauth2/v3/certs
      triggerRules:
      - excludedPaths:
        - exact: /_internal/knative/activator/probe
        - exact: /healthz
        - exact: /probe
        - exact: /metrics
  principalBinding: USE_ORIGIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-knative-serving
 namespace: tutorial
spec:
 rules:
 - from:
   - source:
       namespaces: ["knative-serving"]
   to:
   - operation:
       methods: ["GET"]
       paths: ["/_internal/knative/*","/healthz", "/probe", "/metrics"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-jwt
 namespace: tutorial
spec:
 action: ALLOW
 rules:
 - when:
   - key: request.auth.principal
     values: ["cloudrun-gke-invoker-tutorial@jondonovan-knative.iam.gserviceaccount.com"]
   - key: request.auth.audiences
     values: ["example.com"]
   - key: request.auth.claims[iss]
     values: ["https://accounts.google.com"]
```
