### ISSUE TITLE
outdated istio api

### ISSUE THREAD

**Issue by a7i** [knative-sandbox/net-istio#996]
I am currently using a DestinationRule with load balancer setting of `LEAST_REQUEST` which was introduced in Istio 1.14 ([changelog](https://istio.io/latest/news/releases/1.14.x/announcing-1.14/change-notes/))
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-least-request
  namespace: istio-system
spec:
  host: '*.svc.cluster.local'
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST       # enum not supported by net-istio
```
This is currently preventing reconciliation of ingress due to the following error:
```
failed to list *v1alpha3.DestinationRule: unknown value "LEAST_REQUEST" for enum istio.networking.v1alpha3.LoadBalancerSettings_SimpleLB
```

Turns out that the dependency for istio api is not up to date.
